apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5nlk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0024-tenant/ci10t-776-0024-app/devfile-sample-5nlk@sha256:2735711e2da5f7e230cf616cbd91f9873d0bdaeede13e3a8cfe3d5ddbcfadfe9
        name: my-nodejs
        resources: {}
status: {}
